#!/bin/sh

echo 'checking commit message for pivotal tracker id...'
grep "\[.*#[1234567890]*\] .*" "$1"

if [ $? -eq 1 ]
then
  echo 'You did not link a Pivotal Tracker id!'
  echo 'NOT COMMITTED'
  exit 1
fi

